test: testing import and export records
inveniosoftware-attic/invenio-app-demomarc21 pull request #44
Opened 2017-10-13 12:31 UTC by jbenito3

* Adds a test to load all demo records and then export them to the
  available formats. (related to invenio-records/#169)

2017-10-13 13:08 UTC, ntarocco requested changes

2017-10-13 13:08 UTC, ntarocco commented on tests/unit/test_invenio_app_ils.py
> +                        "/record/{0}/export/{1}".format(recid, 'marcxml')
I think that you forgot the param here:
`"/record/{0}/export/{1}".format(recid, 'marcxml')`
should be
`"/record/{0}/export/{1}".format(recid, fmt)`
?

2017-10-13 13:10 UTC, jbenito3 commented on tests/unit/test_invenio_app_ils.py
> +                        "/record/{0}/export/{1}".format(recid, 'marcxml')
damned! well seen

2017-10-13 13:18 UTC, jbenito3 commented on tests/unit/test_invenio_app_ils.py
> +                        "/record/{0}/export/{1}".format(recid, 'marcxml')
fixed! thanks :)

2017-10-13 15:45 UTC, ntarocco approved these changes

2017-10-16 09:16 UTC, jbenito3 commented
Test won't pass until invenio records is released (due to inveniosoftware/invenio-records#180).

2017-10-20 10:15 UTC, drjova approved these changes

2017-10-20 10:15 UTC, merged